version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - unparam
  settings: {}

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/kusold/mightydns

run:
  timeout: 5m
