name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/renovate-global.js"

jobs:
  renovate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Validate Renovate config
        run: |
          npx --yes --package renovate -- renovate-config-validator .github/renovate.json
